% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Data Analysis},
  pdfauthor={Gencer, Alper Sukru},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{color}
\usepackage{float}

\title{Data Analysis}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Summer Project}
\author{Gencer, Alper Sukru}
\date{October 2, 2020}

\begin{document}
\maketitle

\bigskip

\hypertarget{data-analysis}{%
\section{Data Analysis}\label{data-analysis}}

Here, I run the analysis:

There are two questions that I try to answer:

\begin{enumerate}
  \item If the president's tweets show statistically different sentiment score before/after the issue date of executive order.
  \item If the reaction (likes/mentions) that president's tweets receives before/after the issue date of executive order are statistically different than the montly average. 
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{rm}\NormalTok{(}\DataTypeTok{list =} \KeywordTok{ls}\NormalTok{())}
\NormalTok{gencer_TrumpTweets_}\DecValTok{3}\NormalTok{ <-}\StringTok{ }\KeywordTok{read_csv}\NormalTok{(}\StringTok{"C:/Users/alper/OneDrive/Belgeler/GitHub/python_summer2020/Summer_Project/gencer_TrumpTweets_3.csv"}\NormalTok{)}

\CommentTok{####  There are some problems regarding python/R inconsistency. Let me correct them:}
\KeywordTok{library}\NormalTok{(tidyverse)}
\NormalTok{gencer_TrumpTweets_}\DecValTok{3}\NormalTok{ <-}\StringTok{ }\NormalTok{gencer_TrumpTweets_}\DecValTok{3} \OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{sentiment_bin =} \KeywordTok{ifelse}\NormalTok{(}
\NormalTok{    sentiment_bin }\OperatorTok{==}\StringTok{ "[[ True]]"}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\NormalTok{)}
\NormalTok{gencer_TrumpTweets_}\DecValTok{3}\NormalTok{[,}\KeywordTok{ncol}\NormalTok{(gencer_TrumpTweets_}\DecValTok{3}\NormalTok{)}\OperatorTok{-}\DecValTok{0}\NormalTok{] }\CommentTok{# Cool!}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 22,727 x 1
##    sentiment_bin
##            <dbl>
##  1             1
##  2             1
##  3             1
##  4             1
##  5             1
##  6             1
##  7             0
##  8             0
##  9             0
## 10             0
## # ... with 22,717 more rows
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{####  Let's correct the sentiment format:}
\NormalTok{gencer_TrumpTweets_}\DecValTok{3}\NormalTok{ <-}\StringTok{ }\NormalTok{gencer_TrumpTweets_}\DecValTok{3} \OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{sentiment =} \KeywordTok{gsub}\NormalTok{(}\StringTok{"}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{[|}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{]"}\NormalTok{, }\StringTok{""}\NormalTok{, sentiment))}
\NormalTok{gencer_TrumpTweets_}\DecValTok{3}\NormalTok{[,}\KeywordTok{ncol}\NormalTok{(gencer_TrumpTweets_}\DecValTok{3}\NormalTok{)}\OperatorTok{-}\DecValTok{1}\NormalTok{] }\CommentTok{# Cool!}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 22,727 x 1
##    sentiment 
##    <chr>     
##  1 0.53970174
##  2 0.53066443
##  3 0.50350911
##  4 0.53035888
##  5 0.50053568
##  6 0.50876087
##  7 0.49854986
##  8 0.48930895
##  9 0.49862007
## 10 0.47559445
## # ... with 22,717 more rows
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gencer_TrumpTweets_}\DecValTok{3}\OperatorTok{$}\NormalTok{sentiment <-}\StringTok{ }\KeywordTok{as.numeric}\NormalTok{((gencer_TrumpTweets_}\DecValTok{3}\OperatorTok{$}\NormalTok{sentiment))}
\end{Highlighting}
\end{Shaded}

\bigskip

Now let's find monthly like and retweet averages:

\bigskip

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Let's first correct the date format:}
\KeywordTok{library}\NormalTok{(lubridate)}
\NormalTok{gencer_TrumpTweets_}\DecValTok{3}\OperatorTok{$}\NormalTok{created_date2 <-}\StringTok{ }\KeywordTok{as.Date}\NormalTok{((gencer_TrumpTweets_}\DecValTok{3}\OperatorTok{$}\NormalTok{created_date), }\DataTypeTok{tryFormats =} \KeywordTok{c}\NormalTok{(}\StringTok{"%m/%d/%Y"}\NormalTok{),)}
\NormalTok{gencer_TrumpTweets_}\DecValTok{3}\NormalTok{ <-}\StringTok{ }\NormalTok{gencer_TrumpTweets_}\DecValTok{3} \OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{month =} \KeywordTok{month}\NormalTok{(created_date2), }\DataTypeTok{year =} \KeywordTok{year}\NormalTok{(created_date2))}
\NormalTok{gencer_TrumpTweets_}\DecValTok{3}\OperatorTok{$}\NormalTok{monthyear <-}\StringTok{ }\KeywordTok{paste}\NormalTok{(gencer_TrumpTweets_}\DecValTok{3}\OperatorTok{$}\NormalTok{year, gencer_TrumpTweets_}\DecValTok{3}\OperatorTok{$}\NormalTok{month, }\DataTypeTok{sep =} \StringTok{"-"}\NormalTok{)}


\NormalTok{gencer_TrumpTweets_}\DecValTok{3}\NormalTok{ <-}\StringTok{ }\NormalTok{gencer_TrumpTweets_}\DecValTok{3} \OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(month, year) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{# Monthly like and retweet averages:}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{favorite_monthavrg =} \KeywordTok{round}\NormalTok{(}\KeywordTok{mean}\NormalTok{(favorite_count))) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{retweet_monthavrg =} \KeywordTok{round}\NormalTok{(}\KeywordTok{mean}\NormalTok{(retweet_count))) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{# Deviation from the Monthly like and retweet averages:}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{diff_favorite =}\NormalTok{ favorite_count }\OperatorTok{-}\StringTok{ }\NormalTok{favorite_monthavrg) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{diff_retweet =}\NormalTok{ retweet_count }\OperatorTok{-}\StringTok{ }\NormalTok{retweet_monthavrg)}
\end{Highlighting}
\end{Shaded}

And lastly, let's find monthly sentiment averages:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gencer_TrumpTweets_}\DecValTok{3}\NormalTok{ <-}\StringTok{ }\NormalTok{gencer_TrumpTweets_}\DecValTok{3} \OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(month, year) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{# Monthly like and retweet averages:}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{sentiment_monthavrg =}\NormalTok{ (}\KeywordTok{mean}\NormalTok{(sentiment))) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{sentiment_bin_monthavrg =}\NormalTok{ (}\KeywordTok{mean}\NormalTok{(sentiment_bin))) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{# Deviation from the Monthly like and retweet averages:}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{diff_sentiment =}\NormalTok{ sentiment }\OperatorTok{-}\StringTok{ }\NormalTok{sentiment_monthavrg) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{diff_sentiment_bin =}\NormalTok{ sentiment_bin }\OperatorTok{-}\StringTok{ }\NormalTok{sentiment_bin_monthavrg)}
\end{Highlighting}
\end{Shaded}

\bigskip

\hypertarget{hypothesis-1}{%
\subsection{Hypothesis 1:}\label{hypothesis-1}}

Let's check our first hypothesis that if the president's tweets show
statistically different sentiment score close to the issue date of
executive order:

\hypertarget{a-tibble-22727-x-48}{%
\section{A tibble: 22,727 x 48}\label{a-tibble-22727-x-48}}

\hypertarget{groups-month-year-45}{%
\section{Groups: month, year {[}45{]}}\label{groups-month-year-45}}

\begin{verbatim}
  X1 `Unnamed: 0` source text  created_at created_date created_time
\end{verbatim}

\\
1 0 0 Twitt\textasciitilde{} RT @\textasciitilde{} 1/1/2017
\textasciitilde{} 1/1/2017 06:49\\
2 1 1 Twitt\textasciitilde{} RT @\textasciitilde{} 1/1/2017
\textasciitilde{} 1/1/2017 06:49\\
3 2 2 Twitt\textasciitilde{} RT @\textasciitilde{} 1/1/2017
\textasciitilde{} 1/1/2017 05:44\\
4 3 3 Twitt\textasciitilde{} RT @\textasciitilde{} 1/1/2017
\textasciitilde{} 1/1/2017 05:43\\
5 4 4 Twitt\textasciitilde{} RT @\textasciitilde{} 1/1/2017
\textasciitilde{} 1/1/2017 05:39\\
6 5 5 Twitt\textasciitilde{} TO A\textasciitilde{} 1/1/2017
\textasciitilde{} 1/1/2017 05:00\\
7 6 6 Twitt\textasciitilde{} Chin\textasciitilde{} 1/2/2017
\textasciitilde{} 1/2/2017 23:47\\
8 7 7 Twitt\textasciitilde{} Nort\textasciitilde{} 1/2/2017
\textasciitilde{} 1/2/2017 23:05\\
9 8 8 Twitt\textasciitilde{} I th\textasciitilde{} 1/2/2017
\textasciitilde{} 1/2/2017 18:44\\
10 9 9 Twitt\textasciitilde{} Vari\textasciitilde{} 1/2/2017
\textasciitilde{} 1/2/2017 18:37\\
\# \ldots{} with 22,717 more rows, and 41 more variables: retweet\_count
, \# favorite\_count , is\_retweet , id\_str , int\_1day\_beg , \#
int\_1day\_end , int\_3day\_beg , int\_3day\_end , \# int\_5day\_beg ,
int\_5day\_end , int\_7day\_beg , \# int\_7day\_end , int\_11day\_beg ,
int\_11day\_end , \# int\_15day\_beg , int\_15day\_end ,
\texttt{executive\ order} , \# executive , order , unilateral ,
\texttt{executive\ action} , \# int\_1day , int\_3day , int\_5day ,
int\_7day , \# int\_11day , int\_15day , sentiment , sentiment\_bin , \#
created\_date2 , month , year , monthyear , \# favorite\_monthavrg ,
retweet\_monthavrg , diff\_favorite , \# diff\_retweet ,
sentiment\_monthavrg , \# sentiment\_bin\_monthavrg , diff\_sentiment ,
\# diff\_sentiment\_bin

\begin{figure}[H]
\includegraphics[width=0.5\linewidth]{dataanalysis_gencer_files/figure-latex/Q5-1} \caption{DV = Sentiment}\label{fig:Q5}
\end{figure}

\begin{figure}[H]
\includegraphics[width=0.5\linewidth]{dataanalysis_gencer_files/figure-latex/Q6-1} \includegraphics[width=0.5\linewidth]{dataanalysis_gencer_files/figure-latex/Q6-2} \caption{DV = Number of Likes}\label{fig:Q6}
\end{figure}

\begin{figure}[H]
\includegraphics[width=0.5\linewidth]{dataanalysis_gencer_files/figure-latex/Q7-1} \includegraphics[width=0.5\linewidth]{dataanalysis_gencer_files/figure-latex/Q7-2} \caption{DV = Number of Retweets}\label{fig:Q7}
\end{figure}

\end{document}
